import "./index.html";
import "../common/common-style/common-style.scss";
import "./homepage-style/preview.scss";
import "./homepage-style/about-us.scss";
import "./homepage-style/services.scss";
import "./homepage-style/choouse-us.scss";
import "./homepage-script/accordeon.js";
import "./homepage-style/get-start.scss";
import "../common/common-scripts/sublist.js";
