const dataNews = [
    {
        id: 0,
        tag: 'VR Architecture',
        title: 'Bringing Designs to Life: How VR is Changing Architecture',
        date: 'NASYIYA ULFA | 25 NOV 2022',
        imgs: [
            '/public/articles/vr-event.svg',
            '/public/articles/vr-event.svg',
            '/public/articles/vr-event.svg',
        ],
        description: [
            'Architecture is an art and science that is constantly evolving with technology. The industry has gone through various transformations over the years, from pencil and paper sketches to computer-aided design (CAD) software. However, one technology that is revolutionizing architecture is virtual reality (VR) design.',
            'With VR design, architects can bring their designs to life and offer clients an immersive experience that was previously impossible. The technology enables architects to create a virtual representation of their designs, allowing clients to step into the building and explore its features and spaces before it is built.',
            'VR design is a game-changer for architects and clients alike. It enables architects to design with a greater level of detail and precision, allowing them to identify design flaws and make necessary modifications before construction begins. This not only saves time and money but also ensures that the final product meets the clients expectations.',
            'Clients can also benefit from VR design by having a better understanding of the design and how it will look and feel in real life. It allows them to experience the design in a more realistic way, helping them make informed decisions and providing valuable feedback to the architects.',
            'Moreover, VR design is not only limited to the design phase. It can also be used in the construction process to visualize the projects progress and identify any issues that may arise.',
            'The benefits of VR design in architecture are clear, and the technology is becoming increasingly accessible and affordable. More and more architects and firms are incorporating VR design into their workflows, and the industry is poised for a major transformation.',
            'In conclusion, VR design is changing the way architects design and bring their projects to life. It is a powerful tool that offers a range of benefits, from increased precision and efficiency in the design phase to better communication and understanding with clients. As the technology becomes more advanced and widespread, we can expect to see more innovative designs and better-designed buildings in the future.',
        ],
        postTags: [
            '#VRDesign',
            '#ArchitectureInnovation',
            '#VirtualRealityArchitecture',
            '#BringingDesignsToLife',
            '#DesignVisualization',
            '#ArchitecturalVisualization',
            '#RevolutionizingArchitecture',
            '#BuildingInVR',
            '#DesignThinking',
            '#VRInArchitecture',
        ],
        links: [
            'https://www.google.com',
            'https://www.google.com',
            'https://www.google.com',
        ],
    },
    {
        id: 1,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-1.svg',
            '/public/articles/vr-games-2.svg',
            '/public/articles/vr-games-3.svg',
        ],
        description: [
            'Virtual reality is transforming the gaming industry, offering players a unique immersive experience.',
            'Modern VR games allow not only to observe but to interact with the virtual world.',
            'With each year, technology becomes more accessible and the number of quality VR games grows.',
        ],
        postTags: ['#VRGames', '#VirtualReality', '#ImmersiveExperience'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
    {
        id: 2,
        tag: 'VR Event',
        title: 'Exploring New Worlds: The Benefits of VR Travel',
        date: 'MARIA PETROVA | 5 MAR 2023',
        imgs: [
            '/public/articles/vr-event.svg',
            '/public/articles/slide-1.webp',
            '/public/articles/slide-2.webp',
        ],
        description: [
            'VR travel allows you to explore the most remote corners of the planet without leaving your home.',
            "It's a great way to discover new cultures and attractions in a safe and accessible way.",
            'VR technology opens new horizons for education and entertainment.',
        ],
        postTags: ['#VRTravel', '#VirtualTour', '#ExploreTheWorld'],
        links: [
            'https://www.vrtravel.com',
            'https://www.lonelyplanet.com/vr',
            'https://www.nationalgeographic.com/vr',
        ],
    },
    {
        id: 3,
        tag: 'VR Entertainment',
        title: 'Making Events Memorable: The Power of VR for Corporate and Special Occasions',
        date: 'JOHN DOE | 12 FEB 2023',
        imgs: [
            '/public/articles/vr-entertainment.svg',
            '/public/articles/slide-3.webp',
            '/public/articles/slide-4.webp',
        ],
        description: [
            'VR is revolutionizing the way we experience events, making them more interactive and memorable.',
            'From corporate meetings to private parties, VR brings a new level of engagement.',
            'Event organizers are increasingly adopting VR to stand out and impress their guests.',
        ],
        postTags: ['#VREvents', '#VirtualReality', '#EventTech'],
        links: [
            'https://www.eventbrite.com/vr',
            'https://www.vrevent.com',
            'https://www.techradar.com/vr-events',
        ],
    },
    {
        id: 4,
        tag: 'VR Education',
        title: 'The Future of Education: How VR is Revolutionizing the Classroom',
        date: 'IRINA SMIRNOVA | 18 FEB 2023',
        imgs: [
            '/public/articles/vr-edication.svg',
            '/public/articles/slide-3.webp',
            '/public/articles/slide-4.webp',
        ],
        description: [
            'Education with VR becomes more interactive and engaging.',
            'Students can study complex topics by immersing themselves in virtual labs and historical events.',
            'VR helps make learning accessible to everyone, regardless of location.',
        ],
        postTags: ['#VREducation', '#EdTech', '#VirtualClassroom'],
        links: [
            'https://www.edutopia.org/vr',
            'https://www.vrclassroom.com',
            'https://www.educationnext.org/vr',
        ],
    },
    {
        id: 5,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-4.svg',
            '/public/articles/vr-games-5.svg',
            '/public/articles/vr-games-1.svg',
        ],
        description: [
            'VR gaming is not just a trend, but a new era in the entertainment industry.',
            'Players can now experience games in a way that was previously impossible.',
            'The future of gaming is closely tied to the development of VR technologies.',
        ],
        postTags: ['#VRGames', '#NextGenGaming', '#VirtualReality'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
    {
        id: 6,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-2.svg',
            '/public/articles/vr-games-3.svg',
            '/public/articles/vr-games-4.svg',
        ],
        description: [
            'The popularity of VR games is growing rapidly around the world.',
            'Developers are creating more realistic and engaging virtual worlds.',
            'VR gaming offers new opportunities for social interaction and creativity.',
        ],
        postTags: ['#VRGames', '#VirtualWorlds', '#GamingCommunity'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
    {
        id: 7,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-5.svg',
            '/public/articles/vr-games-1.svg',
            '/public/articles/vr-games-2.svg',
        ],
        description: [
            'VR gaming is changing the way we play and experience digital entertainment.',
            'With VR, players are not just spectators but active participants in the game.',
            'The boundaries between reality and the virtual world are becoming increasingly blurred.',
        ],
        postTags: ['#VRGames', '#ImmersiveGaming', '#FutureOfEntertainment'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
    {
        id: 8,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-5.svg',
            '/public/articles/vr-games-1.svg',
            '/public/articles/vr-games-2.svg',
        ],
        description: [
            'VR gaming is changing the way we play and experience digital entertainment.',
            'With VR, players are not just spectators but active participants in the game.',
            'The boundaries between reality and the virtual world are becoming increasingly blurred.',
        ],
        postTags: ['#VRGames', '#ImmersiveGaming', '#FutureOfEntertainment'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
    {
        id: 9,
        tag: 'VR Games',
        title: 'Entertainment Goes Virtual: The Rise of VR Gaming',
        date: 'ALEXEY IVANOV | 10 JAN 2023',
        imgs: [
            '/public/articles/vr-games-5.svg',
            '/public/articles/vr-games-1.svg',
            '/public/articles/vr-games-2.svg',
        ],
        description: [
            'VR gaming is changing the way we play and experience digital entertainment.',
            'With VR, players are not just spectators but active participants in the game.',
            'The boundaries between reality and the virtual world are becoming increasingly blurred.',
        ],
        postTags: ['#VRGames', '#ImmersiveGaming', '#FutureOfEntertainment'],
        links: [
            'https://www.vrnews.com/games',
            'https://www.ign.com/vr',
            'https://www.gamespot.com/vr',
        ],
    },
]
export default dataNews
